addd testing part in yml file

diff --git a/.github/workflows/docker-build.yml b/.github/workflows/docker-build.yml
--- a/.github/workflows/docker-build.yml
+++ b/.github/workflows/docker-build.yml
@@ -17,4 +17,16 @@ jobs:
       run: docker build -t frontend-only-app .
 
     - name: Run Docker Container
-      run: docker run -d -p 3000:3000 frontend-only-app
+      run: docker run -d -p 3000:3000 --name running-frontend-app frontend-only-app
+
+    - name: Wait for container to initialize
+      run: sleep 5
+
+    - name: Test if app is running using curl
+      run: |
+        if curl -s http://localhost:3000 > /dev/null; then
+          echo "App is running successfully!"
+        else
+          echo "App failed to run."
+          exit 1
+        fi
